# Workflow name that will appear in the Actions tab
name: Run Laravel Tests

# Trigger: When this workflow will run
on:
  # Trigger on push events on the main and dev branches
  push:
    branches: ["main", "dev"]
  # Trigger on pull request events on the main and dev branches
  pull_request:
    branches: ["main", "dev"]

# List of jobs that will be run
jobs:
  # We define a job with ID 'laravel-tests'
  laravel-tests:
    # Run the job on an ubuntu-latest environment
    runs-on: ubuntu-latest

    # Steps that will be executed
    steps:
      # Step 1: Checkout code from repository
      # This step checks out your repository under $GITHUB_WORKSPACE, so your
      # workflow can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup PHP with required extensions for Laravel
      # Using popular action from shivammathur to setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # We need PHP 8.3 for Laravel
          php-version: "8.3"
          # We need these PHP extensions for Laravel
          extensions: mbstring, xml, ctype, fileinfo, curl, dom, pdo, sqlite, pdo_sqlite
          # Composer 2 is the default tool for managing dependencies
          tools: composer:v2
          # We don't need code coverage for this workflow
          coverage: none

      # Step 3: Install dependencies via Composer
      # --no-progress, --prefer-dist, and --optimize-autoloader are standard flags for CI
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      # Step 4: Install NPM dependencies
      - name: Install NPM dependencies
        run: npm ci

      # Step 5: Build assets
      - name: Build assets
        run: npm run build

      # Step 6: Prepare .env file for testing
      # Laravel requires .env file to avoid errors when running artisan
      - name: Prepare environment file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Step 7: Generate Application Key
      # Application key must exist before running tests
      - name: Generate application key
        run: php artisan key:generate

      # Step 8: Run tests using Artisan
      # The core command you requested
      - name: Run Pest/PHPUnit tests
        run: php artisan test
